heat_template_version: 2013-05-23

description: Template to deploy Wordpress Website with MariaDB Server

parameters:
  public_net:
        type: string
        description: public network id

  key_name:
    type: string
    description: Name of a KeyPair to enable SSH access to the instance
    default: mykey

  instance_type:
    type: string
    description: Instance type for web and DB servers
    default: m1.medium
    constraints:
      - allowed_values: [m1.tiny, m1.small, m1.medium, m1.large, m1.xlarge]
        description: instance_type must be a valid instance type

  image_id:
    type: string
    description: Name or ID of the image to use for the WordPress server.    
    default: Centos7_Cloud

  db_name:
    type: string
    description: WordPress Database Name
    default: wordpress
    constraints:
      - length: { min: 1, max: 64 }
        description: db_name must be between 1 and 64 characters
      - allowed_pattern: '[a-zA-Z][a-zA-Z0-9]*'
        description: >
          db_name must begin with a letter and contain only alphanumeric
          characters
  db_username:
    type: string
    description: The WordPress database admin account username
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 16 }
        description: db_username must be between 1 and 16 characters
      - allowed_pattern: '[a-zA-Z][a-zA-Z0-9]*'
        description: >
          db_username must begin with a letter and contain only alphanumeric
          characters
  db_password:
    type: string
    description: The WordPress database admin account password
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 41 }
        description: db_password must be between 1 and 41 characters
      - allowed_pattern: '[a-zA-Z0-9]*'
        description: db_password must contain only alphanumeric characters

  db_root_password:
    type: string
    description: Root password for MySQL
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 41 }
        description: db_root_password must be between 1 and 41 characters
      - allowed_pattern: '[a-zA-Z0-9]*'
        description: db_root_password must contain only alphanumeric characters
      
resources:
  server_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Securitygroup for Web
      name: web-security-group
      rules: [
        {remote_ip_prefix: 0.0.0.0/0,
        protocol: tcp,
        port_range_min: 22,
        port_range_max: 22},        
        {remote_ip_prefix: 0.0.0.0/0,
        protocol: tcp,
        port_range_min: 80,
        port_range_max: 80},
        {remote_ip_prefix: 0.0.0.0/0,
        protocol: icmp}]

  private_net:
        type: OS::Neutron::Net
        properties:
          name: private-net

  private_subnet:
        type: OS::Neutron::Subnet
        properties:
          network_id: { get_resource: private_net }
          cidr: 10.0.1.0/24
          gateway_ip: 10.0.1.1
        

  router1:
        type: OS::Neutron::Router
        properties:
          external_gateway_info:
                network: { get_param: public_net }

  router1_interface:
        type: OS::Neutron::RouterInterface
        properties:
          router_id: { get_resource: router1 }
          subnet_id: { get_resource: private_subnet }
   
  server1_port:
        type: OS::Neutron::Port
        properties:
          network_id: { get_resource: private_net }
          fixed_ips:
                - subnet_id: { get_resource: private_subnet }
  

  DatabaseServer:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      networks:
        - port: { get_resource: server1_port }
      key_name: { get_param: key_name }
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v
            sed -i "s/metalink=https/metalink=http/" /etc/yum.repos.d/*
            yum -y install mariadb mariadb-server
            touch /var/log/mariadb/mariadb.log
            chown mysql.mysql /var/log/mariadb/mariadb.log
            systemctl start mariadb.service
            # Setup MySQL root password and create a user
            mysqladmin -u root password db_rootpassword
            cat << EOF | mysql -u root --password=db_rootpassword
            CREATE DATABASE db_name;
            GRANT ALL PRIVILEGES ON db_name.* TO "db_user"@"%"
            IDENTIFIED BY "db_password";
            FLUSH PRIVILEGES;
            EXIT
            EOF
          params:
            db_rootpassword: { get_param: db_root_password }
            db_name: { get_param: db_name }
            db_user: { get_param: db_username }
            db_password: { get_param: db_password }  

  server2_port:
        type: OS::Neutron::Port
        properties:
          network_id: { get_resource: private_net }
          fixed_ips:
                - subnet_id: { get_resource: private_subnet }
          security_groups: [{ get_resource: server_security_group }]
          

  server2_floating_ip:
        type: OS::Neutron::FloatingIP
        properties:
          floating_network_id: { get_param: public_net }
          port_id: { get_resource: server2_port }
          
  WebServer:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      networks:
        - port: { get_resource: server2_port }
      key_name: { get_param: key_name }
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v
            yum -y install httpd wget unzip -y
            yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm
            yum --enablerepo=remi-php74 install -y php php-bz2 php-mysql php-curl php-gd php-intl php-common php-mbstring php-xml
            systemctl restart httpd
            cd /var/www/html/
            wget https://wordpress.org/latest.zip
            unzip latest.zip
            chown -R apache:apache /var/www/html/
            cd wordpress
            cp wp-config-sample.php wp-config.php
            sed -i s/database_name_here/db_name/ wp-config.php
            sed -i s/username_here/db_user/ wp-config.php
            sed -i s/password_here/db_password/ wp-config.php
            sed -i s/localhost/db_ipaddr/ wp-config.php
            setenforce 0 # Otherwise net traffic with DB is disabled
            systemctl restart httpd
          params:
            db_rootpassword: { get_param: db_root_password }
            db_name: { get_param: db_name }
            db_user: { get_param: db_username }
            db_password: { get_param: db_password }
            db_ipaddr: { get_attr: [DatabaseServer, first_address] } 

 
outputs:
  WebsiteURL:
    description: URL for Wordpress Page
    value:
      str_replace:
        template: http://IP/wordpress
        params:
          host: { get_attr: [ WebServer, first_address] }
          IP: { get_attr: [server2_floating_ip, floating_ip_address] }